### ISSUE TITLE
use of requests package

### ISSUE THREAD

**Issue by rosscdh** [instana/python-sensor#125]
Hi there as per the documentation here https://docs.instana.io/quick_start/api/#rest-api

```
from instana.api import APIClient
c = APIClient(base_url="https://<dashboard-url>", api_token='MY_API_TOKEN')

# Or, alternatively if you have the environment variables set
# c = APIClient()

# Retrieve the current application view
av = c.application_view()
av.json()
```

which currently breaks due to requests not being present in the calls, which make use of urllib3 and NOT the requests package for some reason?

```
The API currently uses the requests package to make the REST calls to the API.
As such, requests response objects are returned from API calls.
```

~is this intended as such? or is requests simply a dependency that needs to be installed?~ requests seems to be prepackaged but not implemented it seems that `ob._body` is necessary to be called.. 

or do you plan on using raw urllib3? in which case the docs need to be updated?

**Comment by pglombardo** [comment]
This API client has fallen out of sync and is now deprecated.  Closing this issue.  Thanks @rosscdh  for filing and providing input.
