### ISSUE TITLE
asyncio (libs) support

### ISSUE THREAD

**Issue by arnulfojr** [instana/python-sensor#127]
Hello,

I wanted to ask if you guys have planned to support any asyncio libraries out of the box? e.g., aiohttp (client and server) or sanic.

**Comment by pglombardo** [comment]
Hi @arnulfojr - aiohttp is currently in progress and should be in the next Python package release.  I don't believe Sanic is scheduled currently.  Could you file a feature request at the link below so we can track and update you once it's happening/released? 

https://support.instana.com/hc/en-us/requests/new

I'll close this if there are no other questions but feel free to re-open or file another issue.  Thanks!

**Comment by arnulfojr** [comment]
Nice! thanks! aiohttp is way more than enough!
