### ISSUE TITLE
aiohttp middleware returns None if handler raises

### ISSUE THREAD

**Issue by ddegirmenci** [instana/python-sensor#193]
https://github.com/instana/python-sensor/blob/master/instana/instrumentation/aiohttp/server.py#L40 calling the handler is wrapped in a try-except block, that logs and discards the exception: https://github.com/instana/python-sensor/blob/master/instana/instrumentation/aiohttp/server.py#L56

This causes issues with the utility exceptions provided in aiohttp.web_exceptions, and conflicts with the behaviour other middleware can implement based on exceptions a handler would raise.

**Comment by pglombardo** [comment]
Hi @ddegirmenci thanks for pointing this out.  Let me take a looks and see if I can release a fix soon.

**Comment by ddegirmenci** [comment]
Additionally, the `init_with_instana` function places the middleware at the end of the list, which means that any extra processing (changing status codes, anything that could cause increased response time etc.) will be left out of monitoring -- if I understand everything correctly. Either making sure the middleware is the first in that order, or utilizing another mechanism (signals?) could help with that.

**Comment by pglombardo** [comment]
That's a good point.  We usually put ourselves first in the list for other frameworks and languages.  I'll add this in to the improvements.

**Comment by ddegirmenci** [comment]
Hi @pglombardo, do you have any news for us? Perhaps a public issue tracker we can follow?

**Comment by mmanciop** [comment]
Hi @ddegirmenci,

we will update this issue when resolved. We are a bit swamped with end-of-year business :-)

You may also wanna file a ticket under support.instana.com, but frankly that’s optional given you opened a well-defined issue in GitHub.

Best,
  Michele

**Comment by pglombardo** [comment]
Hey @ddegirmenci if you want to post the same pull request here I'd be happy to merge it.

**Comment by pglombardo** [comment]
This has been fixed in [Instana package  1.17.1](https://pypi.org/project/instana/1.17.1/).

https://github.com/instana/python-sensor/releases/tag/1.17.1

Thanks for pointing this out!
