### ISSUE TITLE
urllib3 will drop support for Python 2.7 & 3.5 in v.2.0

### ISSUE THREAD

**Issue by manojpandey** [instana/python-sensor#307]
⚠️ IMPORTANT: urllib3 v2.0 will drop support for Python 2: [Read more in the v2.0 Roadmap](https://urllib3.readthedocs.io/en/latest/v2-roadmap.html#optimized-for-python-3-6)

https://github.com/urllib3/urllib3/releases/tag/1.26.4

**Comment by Ferenc-** [comment]
Moved to Kanbanize, closing for now.
