### ISSUE TITLE
pip & Python 2 support

### ISSUE THREAD

**Issue by manojpandey** [instana/python-sensor#308]
[Python 2 Support for pip](https://pip.pypa.io/en/stable/development/release-process/#python-2-support)

> pip 20.3 was the last version of pip that supported Python 2. Bugs reported with pip which only occur on Python 2.7 will likely be closed as “won’t fix” issues by pip’s maintainers.

**Comment by Ferenc-** [comment]
Moved to Kanbanize, closing for now.
