### ISSUE TITLE
Need a way to set app wide service name

### ISSUE THREAD

**Issue by pglombardo** [instana/python-sensor#48]
The sensor currently lacks a way for users to set a global service name for their application.

If the user instantiates a tracer themselves, they can then set the service name via `Options` for all traces generated with that tracer but there is no method for default sensor instantiation.

Current idea is to add two separate methods.  One via environment variable and the second via code.

e.g. `export INSTANA_SERVICE_NAME=myservice` or via code `instana.service_name = "myservice"`

**Comment by hughbrien** [comment]
Developers sometimes require a method for overriding Service Names during Development, Testing and Deployment.

**Comment by pglombardo** [comment]
This has been added in #50.  Thanks for the report @hughbrien!
