### ISSUE TITLE
[Bug]: python-sensor overrides funcName which logs the message with log_with_instana

### ISSUE THREAD

**Issue by staaam** [instana/python-sensor#563]
### Problem Description

Instana python-sensor overrides funcName which logs the message with `log_with_instana` 

Impact: we're writing funcName for every message for easier understanding of the message origin, and currently we see `log_with_instana` in all places instead.

### Minimal, Complete, Verifiable, Example

```python
import logging


def random_func():
    logging.info("Hello, world")


if __name__ == '__main__':
    logging.basicConfig(level=logging.INFO, format="funcName:%(funcName)s message:%(message)s")
    random_func()

    import instana
    random_func()
```

Expected output:
```
funcName:random_func message:Hello, world
funcName:random_func message:Hello, world
```

Actual output:
```
funcName:random_func message:Hello, world
funcName:log_with_instana message:Hello, world
```

### Python Version

Python 3

### Python Modules

```shell
instana @ https://github.com/instana/python-sensor/archive/refs/tags/v2.4.0.zip
```

### Python Environment

```shell
-
```

**Comment by GSVarsha** [comment]
Hi @staaam, thank you for reaching out to us. I just installed the same instana module version with `pip install -e git+https://github.com/instana/python-sensor@v2.4.0#egg=instana` and ran the same snippet you provided and it works fine for me.

```
BEFORE instana import
funcName:random_func message:Hello, world
AFTER instana import
funcName:random_func message:Hello, world
```

**Comment by staaam** [comment]
oh, could it be related to python3.12 ?

**Comment by GSVarsha** [comment]
Hi @staaam, thanks for the update!
Yeah, I checked with python 3.10.13 and it works but when I checked with python 3.11.0 and 3.12.0 I could see the same issue you're facing. 

Is it possible for you to use python 3.10 until we figure out what we could do about this?

**Comment by staaam** [comment]
thanks!
Unfortunately no, we've just recently migrated to python3.12 and go back is not an option.
Worth saying, that at the moment it's not an urgent issue for us, so I think we can wait for this to be fixed...

**Comment by staaam** [comment]
Hey, first of all thanks for fixing!
But unfortunately looks like there was some misunderstanding with affected version, as this issue begins with Python 3.11 (as mentioned here: https://github.com/instana/python-sensor/issues/563#issuecomment-2262135840) but fix applies only for Python 3.13+ :( Any chance to apply this to python 3.11+ instead?

**Comment by staaam** [comment]
thanks! looks like this solves the issue. Any estimation when version with the fix will be released?

**Comment by GSVarsha** [comment]
> thanks! looks like this solves the issue. Any estimation when version with the fix will be released?

Hi @staaam, the fix is already available on the master branch, I will release a new version with the fix before tomorrow and will update you here!

**Comment by GSVarsha** [comment]
Hello @staaam, we've released the version with the fix. You can install using the command below:
```
pip install git+https://github.com/instana/python-sensor@v2.5.3
```

Do let us know if you need anything else, thanks!

**Comment by staaam** [comment]
thank you! 🙏

**Comment by PavinStrickland** [comment]
You're welcome...
